### ISSUE TITLE
What widget does this collector map to?

### ISSUE THREAD

**Issue by gwesterfieldjr** [Hygieia/hygieia-artifact-artifactory-collector#42]
What widget in the dashboard does this collector map to? I don't see an artifact widget by default. Any help on proper way to use this would be great.

**Comment by rvema** [comment]
unfortunately there is no widget corresponding to the data collected by this  collector. Its being used for some decisioning logic implemented in api-audit and api components

**Comment by gwesterfieldjr** [comment]
OK thanks for the details!
